//
// RideTypeEnum.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** The ID of the ride type */public enum RideTypeEnum: String, Codable {
    case express = "express"
    case comfort = "comfort"
    case luxury = "luxury"
    case electric = "electric"
    case suvExpress = "suv_express"
    case suvComfort = "suv_comfort"
    case suvLuxury = "suv_luxury"
    case suvElectric = "suv_electric"
    case wav = "wav"
}