//
// RideInput.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Represents a requested, ongoing, or finished ride */
public struct RideInput: Codable {


    public var rideType: RideTypeEnum?

    /** Seats requested by the user */
    public var seats: String?

    /** Maximum distance the user would like to walk to the pickup point and from the drop off point to the destination */
    public var walkingDistance: String?

    /** Id that has been assigned to the user at sign up */
    public var userId: String?

    public var originLocation: Location?

    public var destination: Location?
    public init(rideType: RideTypeEnum? = nil, seats: String? = nil, walkingDistance: String? = nil, userId: String? = nil, originLocation: Location? = nil, destination: Location? = nil) { 
        self.rideType = rideType
        self.seats = seats
        self.walkingDistance = walkingDistance
        self.userId = userId
        self.originLocation = originLocation
        self.destination = destination
    }
    public enum CodingKeys: String, CodingKey { 
        case rideType = "ride_type"
        case seats
        case walkingDistance
        case userId
        case originLocation = "origin_location"
        case destination
    }

}
