//
// RideRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Minimal set of ride details */
public struct RideRequest: Codable {


    /** The ID of the requested ride */
    public var vehicleId: String?

    /** The number plate of the vehicle */
    public var numPlate: String?

    /** The model of the car */
    public var model: String?

    /** The color of the car */
    public var color: String?

    /** The origin name as shown to the user */
    public var originName: String?

    /** Approximate time taken for the user to walk to their pickup location */
    public var walkingTimeToPickup: String?

    /** Approximate time taken for the user to reach their destination from the drop off point */
    public var walkingTimeToDestination: String?

    /** Driver&#x27;s contact number to allow the user to contact the driver */
    public var driverNumber: String?

    /** The destination name as shown to the user */
    public var destinationName: String?

    public var status: RideStatusEnum?

    public var pickUp: Location?

    public var dropOff: Location?
    public init(vehicleId: String? = nil, numPlate: String? = nil, model: String? = nil, color: String? = nil, originName: String? = nil, walkingTimeToPickup: String? = nil, walkingTimeToDestination: String? = nil, driverNumber: String? = nil, destinationName: String? = nil, status: RideStatusEnum? = nil, pickUp: Location? = nil, dropOff: Location? = nil) { 
        self.vehicleId = vehicleId
        self.numPlate = numPlate
        self.model = model
        self.color = color
        self.originName = originName
        self.walkingTimeToPickup = walkingTimeToPickup
        self.walkingTimeToDestination = walkingTimeToDestination
        self.driverNumber = driverNumber
        self.destinationName = destinationName
        self.status = status
        self.pickUp = pickUp
        self.dropOff = dropOff
    }
    public enum CodingKeys: String, CodingKey { 
        case vehicleId = "vehicle_id"
        case numPlate = "num_plate"
        case model
        case color
        case originName = "origin_name"
        case walkingTimeToPickup = "walking_time_to_pickup"
        case walkingTimeToDestination = "walking_time_to_destination"
        case driverNumber = "driver_number"
        case destinationName = "destination_name"
        case status
        case pickUp = "pick_up"
        case dropOff = "drop_off"
    }

}
