//
// RideStatusEnum.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** The status of the ride */public enum RideStatusEnum: String, Codable {
    case pending = "pending"
    case accepted = "accepted"
    case arrived = "arrived"
    case pickedup = "pickedUp"
    case droppedoff = "droppedOff"
    case canceled = "canceled"
    case scheduled = "scheduled"
    case unknown = "unknown"
}