//
// RideCancellationResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Returns the ride cancellation status */
public struct RideCancellationResponse: Codable {


    public var status: RideStatusEnum?
    public init(status: RideStatusEnum? = nil) { 
        self.status = status
    }

}
