//
// RideCancellationInput.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct RideCancellationInput: Codable {


    /** The ID of the requested ride */
    public var vehicleId: String?

    /** Id that has been assigned to the user at sign up */
    public var userId: String?
    public init(vehicleId: String? = nil, userId: String? = nil) { 
        self.vehicleId = vehicleId
        self.userId = userId
    }
    public enum CodingKeys: String, CodingKey { 
        case vehicleId = "vehicle_id"
        case userId
    }

}
