//
// DefaultAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class DefaultAPI {
    /**
     - parameter latOrg: (query) Latitude of origin location      - parameter lngOrg: (query) Longitude of origin location      - parameter seats: (query) Number of seats the user wishes to book      - parameter walkingDistance: (query) Distance the user is willing to walk to and from the ride 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getvehiclesGet(latOrg: Double, lngOrg: Double, seats: Int, walkingDistance: Int, completion: @escaping ((_ data: [RideType]?,_ error: Error?) -> Void)) {
        getvehiclesGetWithRequestBuilder(latOrg: latOrg, lngOrg: lngOrg, seats: seats, walkingDistance: walkingDistance).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /getvehicles
     - The getVehicles endpoint returns information about the available vehicles, that fulfils the users' requirements that they have inserted. The response includes the categories of vehicles avaialable, the price and other details about each vehicle, and lists the vehicles in the proper display order.
     - examples: [{contentType=application/json, example=[ {
  "ride_type" : "express",
  "displayName" : "Express",
  "price" : 3.08,
  "pickup" : 993,
  "eta" : 1000
}, {
  "ride_type" : "comfort",
  "displayName" : "Comfort",
  "price" : 5.35,
  "pickup" : 990,
  "eta" : 996
}, {
  "ride_type" : "luxury",
  "displayName" : "Luxury",
  "price" : 8.7,
  "pickup" : 991,
  "eta" : 996
}, {
  "ride_type" : "electric",
  "displayName" : "Electric",
  "price" : 3,
  "pickup" : 989,
  "eta" : 996
}, {
  "ride_type" : "suv_express",
  "displayName" : "SUV Express",
  "price" : 2.8,
  "pickup" : 990,
  "eta" : 1000
}, {
  "ride_type" : "suv_comfort",
  "displayName" : "SUV Comfort",
  "price" : 3.08,
  "pickup" : 991,
  "eta" : 998
}, {
  "ride_type" : "suv_luxury",
  "displayName" : "SUV Luxury",
  "price" : 4.5,
  "pickup" : 988,
  "eta" : 998
}, {
  "ride_type" : "suv_electric",
  "displayName" : "SUV Electric",
  "price" : 3.58,
  "pickup" : 989,
  "eta" : 998
}, {
  "ride_type" : "wav",
  "displayName" : "WAV",
  "price" : 5.6,
  "pickup" : 1000,
  "eta" : 1020
} ]}]
     - parameter latOrg: (query) Latitude of origin location      - parameter lngOrg: (query) Longitude of origin location      - parameter seats: (query) Number of seats the user wishes to book      - parameter walkingDistance: (query) Distance the user is willing to walk to and from the ride 

     - returns: RequestBuilder<[RideType]> 
     */
    open class func getvehiclesGetWithRequestBuilder(latOrg: Double, lngOrg: Double, seats: Int, walkingDistance: Int) -> RequestBuilder<[RideType]> {
        let path = "/getvehicles"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "latOrg": latOrg, 
                        "lngOrg": lngOrg, 
                        "seats": seats.encodeToJSON(), 
                        "walkingDistance": walkingDistance.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<[RideType]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
